
<!DOCTYPE HTML>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta content="Olivet University, where future leaders and scholars are equipped to change the world for Jesus Christ. Olivet University students come from a wide range of age groups, geographical areas, educational backgrounds, and cultural heritages, creating a rich and challenging educational environment." name="description" />
<meta name="keywords" content="Olivet University, Olivet, News, Campus News" />
<meta name="keyphrase" content="Olivet University News, Olivet News" />
<title>Olivet University News - OlivetNews.com</title>
<meta name="msvalidate.01" content="1041215C1BB846E107FFF683F2966CCD" />
<meta name="p:domain_verify" content="0d63b3d3525a4ce3df924cbb2a20d05c" />
<link href="http://www.olivetnews.com/images/favicon.ico" rel="shortcut icon" />
<link href="http://www.olivetnews.com/css/style_olivetnews.css" rel="stylesheet" type="text/css" />
</head>

<body>
    <!-- Header Start -->
    <div id="HeaderBG">
      <div id="HeaderWrapper">
            <div id="Header">
                <h1><a href="index.html" title="Olivet University News"><span class="non_disply"><strong>OLIVET UNIVERSITY NEWS | Olivet News</strong></span></a></h1>
                <div id="HeaderSearchBox">
				<form name="topsearch" action="search.html" id="top_search_box" onSubmit="return chk_search()">
					
						<input type="text" name="q">
					</form>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->
    <!-- Contents Start -->
    <div id="ConWrapLeft">
    	<div id="ConWrapRight">
        	<div id="ContentsWrapper">
            	<div id="Contents">
                	<div id="ConLeft">
			
                        <div id="MainNav">
                            <ul>
                            	
                                 <li ><a href="admin_index.html" title="Olivet University Theology">Manage News</a></li>
                                <li ><a href="admin_category.html" title="Olivet University Theology">Manage Categories</a></li>
                                <li class="Current"><a href="index.html" title="Olivet University General News">Go to Frontend</a></li>
				<li class="lastone"><a href="category.html?opt=ocb" title="Olivet University Business">Log Out</a></li>
                            </ul>
                        </div>
                        
			<style>
                            #MainNewsBox li{margin:10px 0}
                             #MainNewsBox input,  #MainNewsBox select {
                                padding: 1px;
                                margin: 0;
                                font-size: 12pt;
                                border: 1px solid #7F9DB9;
                              }
                        </style>															<!-- MainNews Start -->
                        <div id="MainNewsBox">
                            <h2>Edit Category</h2>
                            <?php 
                            $form->setAttribute('action', $this->url('category_edit',
                                array(
                                    'action'=>'edit',
                                    'id'=>$this->id,
                                    )
                                ));
                            $form->prepare();
                            echo $this->form()->openTag($form);
                            echo $this->formHidden($form->get('csrf'));
                            // $this->form()->setDefault('name',$this->category->getName());
                            ?>
    <div class="form-group">
        <?php echo $this->formHidden($form->get('id'));?>
        <label>Name</label>
        <?php echo $this->formInput($form->get('name'));?>
        <span class="text-danger"><?php echo $this->formElementErrors($form->get('name'));?></span>
    </div>
    <div class="form-group">
        <label >Image</label>
        <?php echo $this->formFile($form->get('imgurl'));?>
        <span class="text-danger"><?php echo $this->formElementErrors($form->get('imgurl'));?></span>
    </div>
    
    <div class="form-group">
        <label>Position</label>
        <?php echo $this->formInput($form->get('position'));?>
        <span class="text-danger"><?php echo $this->formElementErrors($form->get('position'));?></span>
    </div>
    
    <button type="submit" class="btn btn-default">Submit</button>
<?php echo $this->form()->closeTag();?>
                            <br/>
                        </div>
                        <!-- NewsArcheive End -->
                        <!-- Numbering Start -->
                        <ul class="NewsNumbering">
							 <li ><a class='actives' href="/index.htm?page=1"><b>1</b></a></li>  <li><a href="/index.htm?page=2">2</a></li>		 <li><a href="/index.htm?page=3">3</a></li>		 <li><a href="/index.htm?page=4">4</a></li>		 <li><a href="/index.htm?page=5">5</a></li>		 <li><a href="/index.htm?page=6">6</a></li>		 <li><a href="/index.htm?page=7">7</a></li>		 <li><a href="/index.htm?page=8">8</a></li>		<li><a href="/index.htm?page=9">Next ></a></li> 				       	</ul>
                        <!-- Numbering End -->
                        <div class="clear"></div>
                        <br/>
                        
                        <a href="admin_add.html">Add News</a>
                    </div>
                    <div id="ConRight">
                    	<div id="SocialBox">
                        	<ul>
                                <li class="img00"><a href="http://www.facebook.com/TheOlivetUniversity" target="_blank" title="Olivet University Facebook"></a></li>
                                <li class="img01"><a href="https://twitter.com/#!/OlivetUniv" target="_blank" title="Olivet University Twitter"></a></li>
                                <li class="img02"><a href="http://www.flickr.com/photos/olivetuniversity" target="_blank" title="Olivet University Flickr"></a></li>
                                <li class="img03"><a href="https://plus.google.com/116414237970966818430/" target="_blank" title="Olivet University Google Plus"></a></li>
                                <li class="img04"><a href="http://www.youtube.com/OlivetUniv" target="_blank" title="Olivet University Youtube"></a></li>
                                <li class="img05"><a href="http://www.olivetnews.com/rss.php" target="_blank" title="Olivet University RSS"></a></li>
                            </ul>
                        </div>
                        <!-- <div class="RightInfo">
                        	<p>Olivet University is a warm and friendly place to pursue a serious Christian education. Olivet University students come from a wide range of age groups, geographical areas, educational backgrounds, and cultural heritages, creating a rich and challenging educational environment.</p>
                        </div> -->
                        <div class="RightInfo">
                        	<h2>Olivet University Colleges</h2>
                            <ul>
                            	<li><a href="http://otcs.olivetuniversity.edu/" target="_blank" title="Olivet University, Olivet Theological College & Seminary">Olivet Theological College &amp; Seminary</a></li>
                                <li><a href="http://jcm.olivetuniversity.edu/" target="_blank" title="Olivet University, Jubilee College of Music">Jubilee College of Music</a></li>
                                <li><a href="http://ocj.olivetuniversity.edu/" target="_blank" title="Olivet University, Olivet College of Journalism">Olivet College of Journalism</a></li>
                                <li><a href="http://ocad.olivetuniversity.edu/" target="_blank" title="Olivet University, Olivet College of Art & Design">Olivet College of Art &amp; Design</a></li>
                                <li><a href="http://oit.olivetuniversity.edu/" target="_blank" title="Olivet University, Olivet Institute of Technology">Olivet Institute of Technology</a></li>
                                <li><a href="http://ocle.olivetuniversity.edu/" target="_blank" title="Olivet University, Olivet College of Language Education">Olivet College of Language Education</a></li>
                                <li><a href="http://ocb.olivetuniversity.edu/" target="_blank" title="Olivet University, Olivet College of Business">Olivet College of Business</a></li>
                                <li><a href="http://www.olivetuniversity.edu/zinzendorf/" target="_blank" title="Olivet University, Zinzendorf School of Doctoral Studies">Zinzendorf School of Doctoral Studies</a></li>
                            </ul>
                        </div>
                        <div class="RightInfo">
                        	<h2>Olivet University Features</h2>
                            <ul>
                            	<li><a href="http://www.olivetuniversity.edu/library/" target="_blank" title="Olivet University Ralph D. Winter library">Ralph D. Winter library</a></li>
                                <li><a href="http://www.olivetuniversity.edu/donation/" target="_blank" title="Give to Olivet University">Give to Olivet University</a></li>
                                <li><a href="http://olivetyou.com/" target="_blank" title="Olivet University You">Olivet You</a></li>
                                <li><a href="http://olivettheology.com/" target="_blank" title="Olivet University Seminary Blog">Olivet University Seminary Blog</a></li>
                                <li><a href="http://olivetjubileemusic.com/" target="_blank" title="Olivet University Jubilee Music Blog">Olivet University Jubilee Music Blog</a></li>
                                <li><a href="http://olivetjournalism.com/" target="_blank" title="Olivet University Journalism Blog">Olivet Journalism Blog</a></li>
                                <li><a href="http://olivetartdesign.com/" target="_blank" title="Olivet University Art & Design Blog">Olivet Art &amp; Design Blog</a></li>
                                <li><a href="http://olivettech.com/" target="_blank" title="Olivet University Institute of Technology Blog">Olivet Institute of Technology Blog</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Contents End -->
    <div id="Footer">
     	<div id="FooterIn">
        	<div id="FooterCon">
                 <div id="FooterConNew">
            	<div id="FooterConTop">
                <span><a href="http://www.olivetuniversity.edu/" title="OLIVET UNIVERSITY"><span class="non_disply"></span></a></span>
                    <div id="FooterBox1">
                        <h2>ACADEMICS</h2>
                        <ul>
                            <li><a href="http://www.olivetuniversity.edu/aboutolivet/welcome.htm" title="Olivet University Welcome">Welcome</a></li>
                            <li><a href="http://www.olivetuniversity.edu/aboutolivet/history.htm" title="Olivet University History">History</a></li>
                            <li><a href="http://www.olivetuniversity.edu/aboutolivet/mission.htm" title="Olivet University Mission">Mission</a></li>
                            <li><a href="http://www.olivetuniversity.edu/aboutolivet/membership.htm" title="Olivet University Memberships">Memberships</a> </li>
                            <li><a href="http://www.olivetuniversity.edu/aboutolivet/leadership.htm" title="Olivet University Leadership">Leadership</a></li>
                            <li><a href="http://www.olivetuniversity.edu/academics/standards.htm" title="Olivet University Academic Standards">Academic Standards</a></li>
                            <li><a href="http://www.olivetuniversity.edu/academics/rnd.htm" title="Olivet University Research & Development">Research &amp; Development</a></li>
                            <li><a href="http://ir.olivetuniversity.edu/" title="Olivet University Institutional Research">Institutional Research</a></li>
                            <li><a href="http://www.olivetuniversity.edu/library/" title="Olivet University Ralph D. Winter Library">Ralph D. Winter Library</a></li>
                            <li><a href="http://www.olivetuniversity.edu/academics/calendar.htm" title="Olivet University Academic Calendar">Academic Calendar</a></li>
                        </ul>
                    </div>                    
                    <div id="FooterBox2">
                        <h2>ADMISSION</h2>
                        <ul>
                            <li><a href="http://www.olivetuniversity.edu/admission/index.htm" title="Olivet University Admissions Procedure">Admissions Procedure</a></li>
                            <li><a href="http://www.olivetuniversity.edu/admission/under_international.htm" title="Olivet University International Admissions">International Admissions</a></li>
                            <li><a href="http://www.olivetuniversity.edu/admission/graduate_requirements.htm" title="Olivet University Application Requirements">Application Requirements</a></li>
                            <li><a href="http://www.olivetuniversity.edu/admission/under_english.htm" title="Olivet University English">English</a> </li>
                            <li><a href="http://www.olivetuniversity.edu/admission/under_technology.htm" title="Olivet University Technology">Technology</a></li>
                            <li><a href="http://www.olivetuniversity.edu/admission/under_transfer.htm" title="Olivet University Transfer Policy">Transfer Policy</a></li>
                            <li><a href="http://www.olivetuniversity.edu/admission/financial.htm" title="Olivet University Financial Aid">Financial</a></li>
                        </ul>                        
                    </div>
                    <div id="FooterBox3">
                        <h2>Undergraduate</h2>
                        <ul>                        	
                            <li><a href="http://www.olivetuniversity.edu/admission/under_academic.htm#1" title="Olivet University BA Theology">BA Theology</a></li>
                            <li><a href="http://www.olivetuniversity.edu/admission/under_academic.htm#2" title="Olivet University BA Music">BA Music</a></li>
                            <li><a href="http://www.olivetuniversity.edu/admission/under_academic.htm#3" title="Olivet University BA Journalism">BA Journalism</a></li>
                            <li><a href="http://www.olivetuniversity.edu/admission/under_academic.htm#4" title="Olivet University BA Graphic Design">BA Graphic Design</a></li>
                            <li><a href="http://www.olivetuniversity.edu/admission/under_academic.htm#5" title="Olivet University BA Info Technology">BA Info Technology</a></li>
                            <li><a href="http://www.olivetuniversity.edu/admission/graduate_degree.htm#6" title="Olivet University BA Business">BA Business</a></li>
                            <li><a href="http://www.olivetuniversity.edu/admission/graduate_degree.htm#7" title="Olivet University Certificate ESL">Certificate ESL</a></li>
                            <li><a href="http://www.olivetuniversity.edu/admission/graduate_degree.htm#8" title="Olivet University Certificate Language">Certificate Language</a></li>
                        </ul>
                    </div>
                    <div id="FooterBox4">
                        <h2>Graduate</h2>
                        <ul>
                        	<li><a href="http://www.olivetuniversity.edu/admission/graduate_degree.htm#1" title="Olivet University MDiv">MDiv</a></li>
                            <li><a href="http://www.olivetuniversity.edu/admission/graduate_degree.htm#2" title="Olivet University MA Theology">MA Theology</a></li>
                            <li><a href="http://www.olivetuniversity.edu/admission/graduate_degree.htm#3" title="Olivet University MA Music">MA Music</a></li>
                            <li><a href="http://www.olivetuniversity.edu/admission/graduate_degree.htm#4" title="Olivet University MA Journalism">MA Journalism</a></li>
                            <li><a href="http://www.olivetuniversity.edu/admission/graduate_degree.htm#5" title="Olivet University MA Graphic Arts">MA Graphic Arts</a></li>
                            <li><a href="http://www.olivetuniversity.edu/admission/graduate_degree.htm#6" title="Olivet University MA Info Technology">MA Info Technology</a></li> 
                            <li><a href="http://www.olivetuniversity.edu/admission/graduate_degree.htm#8" title="Olivet University MATI">MATI</a></li>
                            <li><a href="http://www.olivetuniversity.edu/admission/graduate_degree.htm#7" title="Olivet University MBA">MBA</a></li>                            
                        </ul>
                    </div>
                    <div id="FooterBox5">
                        <h2>STUDENT LIFE</h2>
                        <ul>
                        	<li><a href="http://www.olivetuniversity.edu/current/studentl.htm" title="Olivet University Student Services">Student Services</a></li>
                            <li><a href="http://www.olivetuniversity.edu/current/spiritual.htm" title="Olivet University Spiritual Formation">Spiritual Formation</a></li>
                            <li><a href="http://www.olivetuniversity.edu/current/campus.htm" title="Olivet University Campus Conduct">Campus Conduct</a></li>
                            <li><a href="http://www.olivetuniversity.edu/current/christian.htm" title="Olivet University Christian Service">Christian Service</a> </li>
                            <li><a href="http://www.olivetuniversity.edu/prospective/resource.htm" title="Olivet University Academic Resource Center">Academic Resource Center</a></li>
                        </ul>                        
                    </div>
                  <div id="FooterBox6">
           	      <h2>CONNECT</h2>
                        <ul>
                        	<li><a href="http://mail.olivetuniversity.edu/" title="Olivet University Webmail">Access Olivet Webmail</a></li>
                            <li><a href="http://www.olivetuniversity.edu/login/my/index1.htm" title="Olivet University E-Campus">E-Campus</a></li>
                            <li><a href="http://www.olivetuniversity.edu/contact/" title="Olivet University Contact">Contact Us</a></li>
                      </ul>
					</div>                   
                </div>                
            </div>
            <div class="clear"></div>
			<div id="FooterConBt">
				&copy; 2015 Olivet University
			</div>
			</div>
		</div>
	</div>
</body>
</html>