

    <!-- Header End -->
    <!-- Contents Start -->
    <div id="ConWrapLeft">
    	<div id="ConWrapRight">
        	<div id="ContentsWrapper">
            	<div id="Contents">
                	<div id="ConLeft">
			<!-- MainNav Start -->
                    <div id="MainNav">
                            <ul>
                                <li class="Current"><a href="http://localhost/olivetnews/public/" title="Olivet University General News">Home</a></li>
                                <?php foreach ($this->categories as $category):?>
                                <li ><a href="category/<?php echo $category->getId();?>" title="<?php echo "Olivet University ".$category->getName();?>"><?php echo $category->getName();?></a></li>
                            <?php endforeach;?>
                            </ul>
                        </div>
                        
                     
            
            <div id="NewsArchiev">
                <?php $i=0;?>
                <?php foreach($this->paginator as $post):
                    $i=$i+1;
                ?>  
                           <?php if(($this->paginator->getCurrentPageNumber()==1)&&($i==1)):?>
                 <div id="MainNewsBox">
                        
            <img src="http://www.olivetuniversity.edu/images_articles/files//Architecture5.jpg" alt="Olivet to Establish New College of Architecture, Engineering and Construction"/>                   
                        <h3><?php echo $post->getCreate_time();?></h3>
                            <h2><a href="/post/view/<?php echo $post->getId();?>"><?php echo $post->getTitle();?></a></h2>
                            <h4><?php echo nl2br($post->getExcerpt());?> <a href="articles/2015/03/06/926/olivet-university-olivet-to-establish-new-college-of-architecture--engineering-and-construction.htm">Read more</a></h4>
                                                        
                        </div>
            <?php else:?>          
                             <h3><?php echo $post->getCreate_time();?></h3>
                           <h2><a href="article.html"><?php echo $post->getTitle();?></a></h2>
                           <p><?php echo $post->getExcerpt();?></p>
                        
            <?php endif;?>             
        <?php endforeach;?>
                        
												</div>
                        <!-- NewsArcheive End -->
                        <!-- Numbering Start -->
                      <?php

 // add at the end of the file after the table

 echo $this->paginationControl(

     // the paginator object

     $this->paginator,

     // the scrolling style

     'sliding',

     // the partial to use to render the control

     'partial/paginator.phtml',

     // the route to link to when a user clicks a control link

     array(

         'route' => 'category_home'

     )

 );

 ?>   
                        <!-- Numbering End -->
                        
                        
                    </div>
                    <div id="ConRight">
                    	<div id="SocialBox">
                        	<ul>
                                <li class="img00"><a href="http://www.facebook.com/TheOlivetUniversity" target="_blank" title="Olivet University Facebook"></a></li>
                                <li class="img01"><a href="https://twitter.com/#!/OlivetUniv" target="_blank" title="Olivet University Twitter"></a></li>
                                <li class="img02"><a href="http://www.flickr.com/photos/olivetuniversity" target="_blank" title="Olivet University Flickr"></a></li>
                                <li class="img03"><a href="https://plus.google.com/116414237970966818430/" target="_blank" title="Olivet University Google Plus"></a></li>
                                <li class="img04"><a href="http://www.youtube.com/OlivetUniv" target="_blank" title="Olivet University Youtube"></a></li>
                                <li class="img05"><a href="http://www.olivetnews.com/rss.php" target="_blank" title="Olivet University RSS"></a></li>
                            </ul>
                        </div>
                        <!-- <div class="RightInfo">
                        	<p>Olivet University is a warm and friendly place to pursue a serious Christian education. Olivet University students come from a wide range of age groups, geographical areas, educational backgrounds, and cultural heritages, creating a rich and challenging educational environment.</p>
                        </div> -->
                        <div class="RightInfo">
                        	<h2>Olivet University Colleges</h2>
                            <ul>
                            	<li><a href="http://otcs.olivetuniversity.edu/" target="_blank" title="Olivet University, Olivet Theological College & Seminary">Olivet Theological College &amp; Seminary</a></li>
                                <li><a href="http://jcm.olivetuniversity.edu/" target="_blank" title="Olivet University, Jubilee College of Music">Jubilee College of Music</a></li>
                                <li><a href="http://ocj.olivetuniversity.edu/" target="_blank" title="Olivet University, Olivet College of Journalism">Olivet College of Journalism</a></li>
                                <li><a href="http://ocad.olivetuniversity.edu/" target="_blank" title="Olivet University, Olivet College of Art & Design">Olivet College of Art &amp; Design</a></li>
                                <li><a href="http://oit.olivetuniversity.edu/" target="_blank" title="Olivet University, Olivet Institute of Technology">Olivet Institute of Technology</a></li>
                                <li><a href="http://ocle.olivetuniversity.edu/" target="_blank" title="Olivet University, Olivet College of Language Education">Olivet College of Language Education</a></li>
                                <li><a href="http://ocb.olivetuniversity.edu/" target="_blank" title="Olivet University, Olivet College of Business">Olivet College of Business</a></li>
                                <li><a href="http://www.olivetuniversity.edu/zinzendorf/" target="_blank" title="Olivet University, Zinzendorf School of Doctoral Studies">Zinzendorf School of Doctoral Studies</a></li>
                            </ul>
                        </div>
                        <div class="RightInfo">
                        	<h2>Olivet University Features</h2>
                            <ul>
                            	<li><a href="http://www.olivetuniversity.edu/library/" target="_blank" title="Olivet University Ralph D. Winter library">Ralph D. Winter library</a></li>
                                <li><a href="http://www.olivetuniversity.edu/donation/" target="_blank" title="Give to Olivet University">Give to Olivet University</a></li>
                                <li><a href="http://olivetyou.com/" target="_blank" title="Olivet University You">Olivet You</a></li>
                                <li><a href="http://olivettheology.com/" target="_blank" title="Olivet University Seminary Blog">Olivet University Seminary Blog</a></li>
                                <li><a href="http://olivetjubileemusic.com/" target="_blank" title="Olivet University Jubilee Music Blog">Olivet University Jubilee Music Blog</a></li>
                                <li><a href="http://olivetjournalism.com/" target="_blank" title="Olivet University Journalism Blog">Olivet Journalism Blog</a></li>
                                <li><a href="http://olivetartdesign.com/" target="_blank" title="Olivet University Art & Design Blog">Olivet Art &amp; Design Blog</a></li>
                                <li><a href="http://olivettech.com/" target="_blank" title="Olivet University Institute of Technology Blog">Olivet Institute of Technology Blog</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
   