<div id="MainNav">
                            <ul>
                            	
                                <li ><a href="/manage" title="Olivet University Theology">Manage News</a></li>
                                <li ><a href="category/manage" title="Olivet University Theology">Manage Categories</a></li>
                                <li class="Current"><a href="/" title="Olivet University General News">Go to Frontend</a></li>
				<li class="lastone"><a href="/admin/logout" title="Olivet University Business">Log Out</a></li>
                            </ul>
                        </div>