   <div id="Footer">
     	<div id="FooterIn">
        	<div id="FooterCon">
                 <div id="FooterConNew">
            	<div id="FooterConTop">
                <span><a href="http://www.olivetuniversity.edu/" title="OLIVET UNIVERSITY"><span class="non_disply"></span></a></span>
                    <div id="FooterBox1">
                        <h2>ACADEMICS</h2>
                        <ul>
                            <li><a href="http://www.olivetuniversity.edu/aboutolivet/welcome.htm" title="Olivet University Welcome">Welcome</a></li>
                            <li><a href="http://www.olivetuniversity.edu/aboutolivet/history.htm" title="Olivet University History">History</a></li>
                            <li><a href="http://www.olivetuniversity.edu/aboutolivet/mission.htm" title="Olivet University Mission">Mission</a></li>
                            <li><a href="http://www.olivetuniversity.edu/aboutolivet/membership.htm" title="Olivet University Memberships">Memberships</a> </li>
                            <li><a href="http://www.olivetuniversity.edu/aboutolivet/leadership.htm" title="Olivet University Leadership">Leadership</a></li>
                            <li><a href="http://www.olivetuniversity.edu/academics/standards.htm" title="Olivet University Academic Standards">Academic Standards</a></li>
                            <li><a href="http://www.olivetuniversity.edu/academics/rnd.htm" title="Olivet University Research & Development">Research &amp; Development</a></li>
                            <li><a href="http://ir.olivetuniversity.edu/" title="Olivet University Institutional Research">Institutional Research</a></li>
                            <li><a href="http://www.olivetuniversity.edu/library/" title="Olivet University Ralph D. Winter Library">Ralph D. Winter Library</a></li>
                            <li><a href="http://www.olivetuniversity.edu/academics/calendar.htm" title="Olivet University Academic Calendar">Academic Calendar</a></li>
                        </ul>
                    </div>                    
                    <div id="FooterBox2">
                        <h2>ADMISSION</h2>
                        <ul>
                            <li><a href="http://www.olivetuniversity.edu/admission/index.htm" title="Olivet University Admissions Procedure">Admissions Procedure</a></li>
                            <li><a href="http://www.olivetuniversity.edu/admission/under_international.htm" title="Olivet University International Admissions">International Admissions</a></li>
                            <li><a href="http://www.olivetuniversity.edu/admission/graduate_requirements.htm" title="Olivet University Application Requirements">Application Requirements</a></li>
                            <li><a href="http://www.olivetuniversity.edu/admission/under_english.htm" title="Olivet University English">English</a> </li>
                            <li><a href="http://www.olivetuniversity.edu/admission/under_technology.htm" title="Olivet University Technology">Technology</a></li>
                            <li><a href="http://www.olivetuniversity.edu/admission/under_transfer.htm" title="Olivet University Transfer Policy">Transfer Policy</a></li>
                            <li><a href="http://www.olivetuniversity.edu/admission/financial.htm" title="Olivet University Financial Aid">Financial</a></li>
                        </ul>                        
                    </div>
                    <div id="FooterBox3">
                        <h2>Undergraduate</h2>
                        <ul>                        	
                            <li><a href="http://www.olivetuniversity.edu/admission/under_academic.htm#1" title="Olivet University BA Theology">BA Theology</a></li>
                            <li><a href="http://www.olivetuniversity.edu/admission/under_academic.htm#2" title="Olivet University BA Music">BA Music</a></li>
                            <li><a href="http://www.olivetuniversity.edu/admission/under_academic.htm#3" title="Olivet University BA Journalism">BA Journalism</a></li>
                            <li><a href="http://www.olivetuniversity.edu/admission/under_academic.htm#4" title="Olivet University BA Graphic Design">BA Graphic Design</a></li>
                            <li><a href="http://www.olivetuniversity.edu/admission/under_academic.htm#5" title="Olivet University BA Info Technology">BA Info Technology</a></li>
                            <li><a href="http://www.olivetuniversity.edu/admission/graduate_degree.htm#6" title="Olivet University BA Business">BA Business</a></li>
                            <li><a href="http://www.olivetuniversity.edu/admission/graduate_degree.htm#7" title="Olivet University Certificate ESL">Certificate ESL</a></li>
                            <li><a href="http://www.olivetuniversity.edu/admission/graduate_degree.htm#8" title="Olivet University Certificate Language">Certificate Language</a></li>
                        </ul>
                    </div>
                    <div id="FooterBox4">
                        <h2>Graduate</h2>
                        <ul>
                        	<li><a href="http://www.olivetuniversity.edu/admission/graduate_degree.htm#1" title="Olivet University MDiv">MDiv</a></li>
                            <li><a href="http://www.olivetuniversity.edu/admission/graduate_degree.htm#2" title="Olivet University MA Theology">MA Theology</a></li>
                            <li><a href="http://www.olivetuniversity.edu/admission/graduate_degree.htm#3" title="Olivet University MA Music">MA Music</a></li>
                            <li><a href="http://www.olivetuniversity.edu/admission/graduate_degree.htm#4" title="Olivet University MA Journalism">MA Journalism</a></li>
                            <li><a href="http://www.olivetuniversity.edu/admission/graduate_degree.htm#5" title="Olivet University MA Graphic Arts">MA Graphic Arts</a></li>
                            <li><a href="http://www.olivetuniversity.edu/admission/graduate_degree.htm#6" title="Olivet University MA Info Technology">MA Info Technology</a></li> 
                            <li><a href="http://www.olivetuniversity.edu/admission/graduate_degree.htm#8" title="Olivet University MATI">MATI</a></li>
                            <li><a href="http://www.olivetuniversity.edu/admission/graduate_degree.htm#7" title="Olivet University MBA">MBA</a></li>                            
                        </ul>
                    </div>
                    <div id="FooterBox5">
                        <h2>STUDENT LIFE</h2>
                        <ul>
                        	<li><a href="http://www.olivetuniversity.edu/current/studentl.htm" title="Olivet University Student Services">Student Services</a></li>
                            <li><a href="http://www.olivetuniversity.edu/current/spiritual.htm" title="Olivet University Spiritual Formation">Spiritual Formation</a></li>
                            <li><a href="http://www.olivetuniversity.edu/current/campus.htm" title="Olivet University Campus Conduct">Campus Conduct</a></li>
                            <li><a href="http://www.olivetuniversity.edu/current/christian.htm" title="Olivet University Christian Service">Christian Service</a> </li>
                            <li><a href="http://www.olivetuniversity.edu/prospective/resource.htm" title="Olivet University Academic Resource Center">Academic Resource Center</a></li>
                        </ul>                        
                    </div>
                  <div id="FooterBox6">
           	      <h2>CONNECT</h2>
                        <ul>
                        	<li><a href="http://mail.olivetuniversity.edu/" title="Olivet University Webmail">Access Olivet Webmail</a></li>
                            <li><a href="http://www.olivetuniversity.edu/login/my/index1.htm" title="Olivet University E-Campus">E-Campus</a></li>
                            <li><a href="http://www.olivetuniversity.edu/contact/" title="Olivet University Contact">Contact Us</a></li>
                      </ul>
					</div>                   
                </div>                
            </div>
            <div class="clear"></div>
			<div id="FooterConBt">
				&copy; 2015 Olivet University
			</div>
			</div>
		</div>
	</div>
</body>
</html>