<!DOCTYPE HTML>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta content="Olivet University, where future leaders and scholars are equipped to change the world for Jesus Christ. Olivet University students come from a wide range of age groups, geographical areas, educational backgrounds, and cultural heritages, creating a rich and challenging educational environment." name="description" />
<meta name="keywords" content="Olivet University, Olivet, News, Campus News" />
<meta name="keyphrase" content="Olivet University News, Olivet News" />
<title>Olivet University News - OlivetNews.com</title>
<meta name="msvalidate.01" content="1041215C1BB846E107FFF683F2966CCD" />
<meta name="p:domain_verify" content="0d63b3d3525a4ce3df924cbb2a20d05c" />
<link href="http://www.olivetnews.com/images/favicon.ico" rel="shortcut icon" />
<link href="http://www.olivetnews.com/css/style_olivetnews.css" rel="stylesheet" type="text/css" />
</head>

<body>
    <!-- Header Start -->
    <div id="HeaderBG">
      <div id="HeaderWrapper">
            <div id="Header">
                <h1><a href="/" title="Olivet University News"><span class="non_disply"><strong>OLIVET UNIVERSITY NEWS | Olivet News</strong></span></a></h1>
               
		<div id="HeaderSearchBox">
			
				<form name="topsearch" action="search.html" id="top_search_box" onSubmit="return chk_search()">
					
						<input type="text" name="q">
					</form>
				
				 <a href="login.html">Admin Login</a>
				
				
                </div>
		
            </div>
        </div>
    </div>