
			
                        
                        
			<style>
                            #MainNewsBox li{margin:10px 0}
                            
                        </style>															<!-- MainNews Start -->
                        <div id="MainNewsBox">
                            <h2>News</h2>
                            <ul>
                            	<?php foreach($this->paginator as $post):?>
                                <li><a href="<?php echo "/post/view/".$post->getId();?>"><?php echo $post->getTitle();?></a>
                                - <a href="<?php echo "/post/edit/".$post->getId();?>">Edit</a> - <a href="<?php echo "/post/delete/".$post->getId();?>">Delete</a>
                                </li>
                                <?php endforeach;?>
                               
                                
                            </ul>
                        </div>
                        <!-- NewsArcheive End -->
                        <!-- Numbering Start -->
                        <ul class="NewsNumbering">
							 <li ><a class='actives' href="/index.htm?page=1"><b>1</b></a></li>  <li><a href="/index.htm?page=2">2</a></li>		 <li><a href="/index.htm?page=3">3</a></li>		 <li><a href="/index.htm?page=4">4</a></li>		 <li><a href="/index.htm?page=5">5</a></li>		 <li><a href="/index.htm?page=6">6</a></li>		 <li><a href="/index.htm?page=7">7</a></li>		 <li><a href="/index.htm?page=8">8</a></li>		<li><a href="/index.htm?page=9">Next ></a></li> 				       	</ul>
                        <!-- Numbering End -->
                        <div class="clear"></div>
                        <br/>
                        
                        <a href="/post/add">Add News</a>
                    </div>