    <div id="ConWrapLeft">
    	<div id="ConWrapRight">
        	<div id="ContentsWrapper">
            	<div id="Contents">
                	<div id="ConLeft">
			<!-- MainNav Start -->
                    	<div id="MainNav">
                      	<ul>
                            	<li><a href="index.html" title="Olivet University General News">Home</a></li>
                                <li class="Current"><a href="category.html?opt=otcs" title="Olivet University Theology">Theology</a></li>
                                <li><a href="category.html?opt=jcm" title="Olivet University Music">Music</a></li>
                                <li><a href="category.html?opt=ocj" title="Olivet University Jounalism">Journalism</a></li>
                                <li><a href="category.html?opt=ocad" title="Olivet University Arts & Design">Arts &amp; Design</a></li>
                                <li><a href="category.html?opt=ocit" title="Olivet University IT">IT</a></li>
				<li class="lastone"><a href="category.html?opt=ocb" title="Olivet University Business">Business</a></li>
                            </ul>
                        </div>
                        <!-- MainNav End -->
							<!-- MainNews Start -->
						  <div id="MainNewsBox">
						  
					<h3>March 06, 2015</h3>
								<h2><a href="/articles/2015/03/06/926/olivet-university-olivet-to-establish-new-college-of-architecture--engineering-and-construction.htm" title="Olivet University - Olivet to Establish New College of Architecture, Engineering and Construction"><?php echo $this->post->getTitle();?></a></h2>
								
								
													<div id="NimgSlide">
						<div id="EnlargeBT">
						<a href="http://www.olivetuniversity.edu/images_articles/files//Architecture2.jpg" rel="lightbox[roadtrip]" title="" style="display:none" id="enlargeA0"><img style="margin-bottom: 0px;" src="/images/news_enlarge_bt.jpg" /> Enlarge this Image</a>						</div>
						<div id="NmainImg"><img id="pic" width="262" src="http://www.olivetuniversity.edu/images_articles/files//thumb/262x0_90/Architecture2.jpg" alt="Olivet University News" /></div>
						
					</div>
					
					<!-- javascript for photoBox end -->
						<!-- slide end  -->
								<p><?php echo nl2br($this->post->getContent());?></p>
							</div>
							<!-- MainNews End -->
						</div>
						<div id="ConRight">
							<div id="SocialBox">
								<ul>
									<li class="img00"><a href="http://www.facebook.com/TheOlivetUniversity" target="_blank" title="Olivet University Facebook"></a></li>
									<li class="img01"><a href="https://twitter.com/#!/OlivetUniv" target="_blank" title="Olivet University Twitter"></a></li>
									<li class="img02"><a href="http://www.flickr.com/photos/olivetuniversity" target="_blank" title="Olivet University Flickr"></a></li>
									<li class="img03"><a href="https://plus.google.com/116414237970966818430/" target="_blank" title="Olivet University Google Plus"></a></li>
									<li class="img04"><a href="http://www.youtube.com/OlivetUniv" target="_blank" title="Olivet University Youtube"></a></li>
									<li class="img05"><a href="http://www.olivetnews.com/rss.php" target="_blank" title="Olivet University RSS News Feeds"></a></li>
								</ul>
							</div>
							<!-- <div class="RightInfo">
								<p>Olivet University is a warm and friendly place to pursue a serious Christian education. Olivet University students come from a wide range of age groups, geographical areas, educational backgrounds, and cultural heritages, creating a rich and challenging educational environment.</p> 
							</div>-->
							<div class="RightInfo">
								<h2>Olivet University Colleges</h2>
								<ul>
									<li><a href="http://otcs.olivetuniversity.edu/" title="Olivet University Theological College & Seminary">Olivet Theological College &amp; Seminary</a></li>
									<li><a href="http://jcm.olivetuniversity.edu/" title="Olivet University Jubilee College of Music">Jubilee College of Music</a></li>
									<li><a href="http://ocj.olivetuniversity.edu/" title="Olivet University College of Journalism">Olivet College of Journalism</a></li>
									<li><a href="http://ocad.olivetuniversity.edu/" title="Olivet University College of Art & Design">Olivet College of Art &amp; Design</a></li>
									<li><a href="http://oit.olivetuniversity.edu/" title="Olivet University Institute of Technology">Olivet Institute of Technology</a></li>
									<li><a href="http://ocle.olivetuniversity.edu/" title="Olivet University College of Language Education">Olivet College of Language Education</a></li>
									<li><a href="http://ocb.olivetuniversity.edu/" title="Olivet University College of Business">Olivet College of Business</a></li>
								</ul>
							</div>
							<div class="RightInfo">
								<h2>Olivet University Features</h2>
								<ul>
									<li><a href="http://www.olivetuniversity.edu/library/" target="_blank" title="Olivet University Ralph D. Winter library">Ralph D. Winter library</a></li>
									<li><a href="http://www.olivetuniversity.edu/donation/" target="_blank" title="Olivet University Give to Olivet University">Give to Olivet University</a></li>
									<li><a href="http://olivetyou.com/" target="_blank"  title="Olivet University You">Olivet You</a></li>
									<li><a href="http://olivettheology.com/" target="_blank"  title="Olivet University Seminary Blog">Olivet University Seminary Blog</a></li>
									<li><a href="http://olivetjubileemusic.com/" target="_blank"  title="Olivet University Jubilee Music Blog">Olivet University Jubilee Music Blog</a></li>
									<li><a href="http://olivetjournalism.com/" target="_blank"  title="Olivet University Journalism Blog">Olivet Journalism Blog</a></li>
									<li><a href="http://olivetartdesign.com/" target="_blank" title="Olivet University Art & Design Blog">Olivet Art & Design Blog</a></li>
									<li><a href="http://olivettech.com/" target="_blank" title="Olivet University Institute of Technology Blog">Olivet Institute of Technology Blog</a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- Contents End -->